#[derive(Clone, Copy)]
pub(super) enum CopyRelation {
    LegacyChange,
    LegacyReceipt,
    LifecycleChange,
    LifecycleRun,
    LifecycleOperation,
    LifecycleOutput,
    LifecycleAttempt,
    LifecycleInput,
    LifecycleReceipt,
    Manifest,
    PipelineRun,
    PipelineAttempt,
    PipelineOutput,
    PipelineInput,
    PipelineReceipt,
    SliceResult,
    PlanningInput,
    PlanningSnapshot,
    ScopeCandidateDraft,
    ScopeCandidateReview,
    CandidateDraft,
    CandidateReview,
    ScopeCandidateReceipt,
    PlanningReceipt,
    SearchResource,
    SearchJob,
    SearchVector,
    MaintenanceSignal,
    MaintenanceTask,
    MaintenanceReceipt,
    MaintenanceConsumer,
    PlanningKnowledgeConsumption,
    ProgramRefreshReceipt,
    Program,
    NativeScope,
}

impl CopyRelation {
    pub(super) const fn name(self) -> &'static str {
        match self {
            Self::LegacyChange => "knowledge_changes",
            Self::LegacyReceipt => "knowledge_command_receipts",
            Self::LifecycleChange => "knowledge_lifecycle_changes",
            Self::LifecycleRun => "knowledge_change_runs",
            Self::LifecycleOperation => "knowledge_change_operations",
            Self::LifecycleOutput => "knowledge_change_outputs",
            Self::LifecycleAttempt => "knowledge_change_attempts",
            Self::LifecycleInput => "knowledge_change_inputs",
            Self::LifecycleReceipt => "knowledge_lifecycle_command_receipts",
            Self::Manifest => "pipeline_knowledge_manifests",
            Self::PipelineRun => "slice_pipeline_runs",
            Self::PipelineAttempt => "slice_pipeline_phase_attempts",
            Self::PipelineOutput => "slice_pipeline_phase_outputs",
            Self::PipelineInput => "slice_pipeline_inputs",
            Self::PipelineReceipt => "slice_pipeline_receipts",
            Self::SliceResult => "slice_results",
            Self::PlanningInput => "slice_planning_inputs",
            Self::PlanningSnapshot => "slice_planning_snapshots",
            Self::ScopeCandidateDraft => "scope_candidate_drafts",
            Self::ScopeCandidateReview => "scope_candidate_reviews",
            Self::CandidateDraft => "slice_candidate_drafts",
            Self::CandidateReview => "slice_candidate_reviews",
            Self::ScopeCandidateReceipt => "scope_candidate_receipts",
            Self::PlanningReceipt => "native_planning_receipts",
            Self::SearchResource => "knowledge_search_resources",
            Self::SearchJob => "knowledge_search_embedding_jobs",
            Self::SearchVector => "knowledge_search_vectors",
            Self::MaintenanceSignal => "knowledge_maintenance_signals",
            Self::MaintenanceTask => "knowledge_maintenance_tasks",
            Self::MaintenanceReceipt => "knowledge_maintenance_command_receipts",
            Self::MaintenanceConsumer => "knowledge_maintenance_consumers",
            Self::PlanningKnowledgeConsumption => "planning_knowledge_consumptions",
            Self::ProgramRefreshReceipt => "program_knowledge_refresh_receipts",
            Self::Program => "programs",
            Self::NativeScope => "native_scopes",
        }
    }
}
