pub(crate) use super::catalog_support::RouteSpec;
use super::catalog_support::{nullable_text, page_limit, text, uuid};
use super::{
    candidate_schema, knowledge_lifecycle_schema, knowledge_maintenance_schema, knowledge_schema,
    knowledge_search_schema, matrix_task_schema, slice_schema,
};
use crate::tools::object_schema;
use serde_json::json;
use std::sync::OnceLock;
use tect_domain::{MAX_SOURCE_PATH_BYTES, MAX_WORKTREES};

macro_rules! route {
    ($tool:expr, $name:expr, $internal:expr, $summary:expr, $conditions:expr,
     $effects:expr, $retry:expr, $schema:expr, $example:expr $(,)?) => {
        RouteSpec {
            tool: $tool,
            route: $name,
            internal: $internal,
            summary: $summary,
            conditions: $conditions,
            effects: $effects,
            retry: $retry,
            schema: $schema,
            example: $example,
        }
    };
}

pub(crate) fn routes() -> &'static [RouteSpec] {
    static ROUTES: OnceLock<Vec<RouteSpec>> = OnceLock::new();
    ROUTES.get_or_init(build_routes)
}

fn build_routes() -> Vec<RouteSpec> {
    let example_id = "00000000-0000-4000-8000-000000000001";
    let mut routes = vec![
        route!(
            "query",
            "program.get",
            "get_program",
            "Read one Program and a bounded page of exact original inputs.",
            "Requires an authenticated open native session and an accessible Program. Omitted after_input starts at the saved input cursor; explicit null is invalid.",
            "Reads a consistent database snapshot only.",
            "Safe to repeat. Follow next_after_input exactly when present.",
            object_schema(
                json!({"program_id":uuid(),"after_input":{"type":"integer","minimum":0},"limit":page_limit()}),
                json!(["program_id"]),
            ),
            json!({"program_id":example_id,"after_input":0,"limit":25}),
        ),
        route!(
            "query",
            "program.list",
            "list_programs",
            "List a bounded Program page with unfinished work first.",
            "Requires an authenticated open native session. Omitted after starts at the first page; explicit null is invalid.",
            "Reads a consistent database snapshot only.",
            "Safe to repeat. Use the returned cursor unchanged.",
            object_schema(
                json!({"after":{"type":"string","pattern":"^[wr]:[0-9a-fA-F-]+$"},"limit":page_limit()}),
                json!([]),
            ),
            json!({"limit":25}),
        ),
        route!(
            "query",
            "source.list",
            "list_sources",
            "List a bounded page of registered worktrees.",
            "Requires an authenticated open native session. Omitted after starts at the first page; explicit null is invalid.",
            "Reads the workspace and host scoped source catalog only.",
            "Safe to repeat. Use next_after unchanged when present.",
            object_schema(
                json!({"after":uuid(),"limit":{"type":"integer","minimum":1,"maximum":MAX_WORKTREES}}),
                json!(["limit"]),
            ),
            json!({"limit":25}),
        ),
        route!(
            "query",
            "task.source.get",
            "get_matrix_task",
            "Read the current immutable Engineering Matrix source revision for one task.",
            "Requires an authenticated native session bound to the task's workspace.",
            "Reads the current task source revision and its recorded identity and digest.",
            "Safe to repeat; a missing task returns not_found.",
            object_schema(json!({"task_id":uuid()}), json!(["task_id"])),
            json!({"task_id":example_id}),
        ),
        route!(
            "query",
            "engineering.matrix.disposition.get",
            "get_matrix_disposition",
            "Read one saved explicit Matrix disposition by task and request ID.",
            "Requires an authenticated native session bound to the task workspace; both IDs must be non-nil.",
            "Reads the immutable typed decision, actor/session provenance, and binding digests without raw Jev content.",
            "Safe to repeat; an absent request returns not_found.",
            object_schema(
                json!({"task_id":uuid(),"request_id":uuid()}),
                json!(["task_id", "request_id"])
            ),
            json!({"task_id":example_id,"request_id":"00000000-0000-4000-8000-000000000002"}),
        ),
        route!(
            "query",
            "setup.get",
            "get_setup",
            "Read a setup draft, exact input page, and current file observation.",
            "Requires an authenticated open native session, its bound task directory, current setup grant, and an accessible setup. Omitted after_input uses saved coverage; explicit null is invalid.",
            "Reads the database and explicitly revalidates the bound AGENTS.md target without writing it.",
            "Safe to repeat. Recovery should start with after_input 0.",
            object_schema(
                json!({"setup_id":uuid(),"after_input":{"type":"integer","minimum":0},"limit":page_limit()}),
                json!(["setup_id"]),
            ),
            json!({"setup_id":example_id,"after_input":0,"limit":25}),
        ),
        route!(
            "command",
            "workspace.open",
            "open_workspace",
            "Create or recover this native session's logical workspace binding.",
            "Requires valid native identity, host credential, tenant, and configured workspace key. A verifier requires an existing workspace and explicit membership.",
            "Owners may create missing workspace, membership, session, and creation events. Verifiers create only their native session and receive no owner workflow actions.",
            "Idempotent for the same authenticated host, native session, and workspace key.",
            object_schema(json!({}), json!([])),
            json!({}),
        ),
        route!(
            "command",
            "source.register",
            "register_source",
            "Register one existing Git worktree in the logical workspace.",
            "Requires an authenticated open session and a canonical Git worktree/common directory under current source grants.",
            "Reads Git identity and atomically records repository/worktree rows; it never changes Git.",
            "Idempotent for the same physical worktree.",
            object_schema(
                json!({"path":{"type":"string","minLength":1,"maxLength":MAX_SOURCE_PATH_BYTES}}),
                json!(["path"]),
            ),
            json!({"path":"/absolute/source/worktree"}),
        ),
        route!(
            "command",
            "task.source.record",
            "record_matrix_task",
            "Record one exact Engineering Matrix factual input revision and optional owner-authored engineering alternatives for a task.",
            "Requires an authenticated open native session, non-nil task and request IDs, revision 1 or the immediate successor of the expected current revision, valid tagged factual input and an optional choice set bound to the exact task/revision. Combined input and choice-set JSON is capped at 1 MiB; at most 1024 reported facts and five candidates. Zero or one candidate is recorded but not eligible for ranking. Choice-set assumptions must reference Matrix fact IDs in this input.",
            "Atomically stores the immutable revision, input digest, and optional choice-set digest in this workspace; source authority remains bound to the native session.",
            "Repeat the same request_id with identical revision, input, and choice set. On uncertainty, read task.source.get before another write.",
            object_schema(
                json!({"task_id":uuid(),"revision":{"type":"integer","minimum":1},"expected_current_revision":{"type":"integer","minimum":0},"request_id":uuid(),"input":matrix_task_schema::input(),"choice_set":matrix_task_schema::choice_set()}),
                json!([
                    "task_id",
                    "revision",
                    "expected_current_revision",
                    "request_id",
                    "input"
                ])
            ),
            json!({"task_id":example_id,"revision":1,"expected_current_revision":0,"request_id":"00000000-0000-4000-8000-000000000002","input":matrix_task_schema::example(),"choice_set":matrix_task_schema::example_choice_set(example_id)}),
        ),
        route!(
            "command",
            "engineering.matrix.verify",
            "verify_matrix_task",
            "Verify the saved Engineering Matrix facts against immutable evidence references.",
            "Requires an authenticated verifier native session bound to the workspace, an exact saved task revision and input digest, and one evidence reference per required fact. The verifier must differ from the owner who recorded the revision. Evidence validation is disabled by default.",
            "On successful evidence validation, appends a sealed verification record. The response is a bounded digest and per-fact status receipt without raw evidence content.",
            "On uncertainty, inspect the saved task revision; avoid retrying with changed evidence. Verification remains unavailable until a trusted evidence validator is configured.",
            object_schema(
                json!({
                    "task_id":uuid(),
                    "expected_revision":{"type":"integer","minimum":1},
                    "input_digest":{"type":"string","pattern":"^[0-9a-fA-F]{64}$"},
                    "evidence":{"type":"array","maxItems":1040,"items":object_schema(
                        json!({"fact_path":{"type":"string","minLength":1,"maxLength":512,"pattern":"^/"},"evidence_ref":{"type":"string","minLength":1,"maxLength":4096,"pattern":"\\S"}}),
                        json!(["fact_path","evidence_ref"])
                    )}
                }),
                json!(["task_id", "expected_revision", "input_digest", "evidence"])
            ),
            json!({"task_id":example_id,"expected_revision":1,"input_digest":"0".repeat(64),"evidence":[{"fact_path":"/mode","evidence_ref":"urn:evidence:example"}]}),
        ),
        route!(
            "query",
            "engineering.matrix.planning_effect.get",
            "get_matrix_planning_effect",
            "Read the exact selected Matrix choice and saved planning nodes for independent review.",
            "Requires an authenticated verifier native session, the selected candidate set ID, and the caller receipt request ID.",
            "Reads saved choice and mapped node bodies with a canonical effect digest; no planning state changes.",
            "Safe to repeat. Use the returned revision and digest for a separate attestation.",
            object_schema(
                json!({"candidate_set_id":uuid(),"caller_request_id":uuid()}),
                json!(["candidate_set_id", "caller_request_id"])
            ),
            json!({"candidate_set_id":example_id,"caller_request_id":"00000000-0000-4000-8000-000000000002"}),
        ),
        route!(
            "command",
            "engineering.matrix.planning_effect.verify",
            "verify_matrix_planning_effect",
            "Append an independent attestation of one saved Matrix planning effect.",
            "Requires an authenticated verifier native session separate from the Matrix owner and caller, exact current result revision and effect digest, and a bounded summary.",
            "Appends a match or rejection attestation; it does not mutate planning readiness or call Jev.",
            "Retry only with the same request_id and identical fields.",
            object_schema(
                json!({
                    "request_id":uuid(),"candidate_set_id":uuid(),"caller_request_id":uuid(),
                    "expected_result_revision":{"type":"integer","minimum":1},
                    "expected_effect_digest":{"type":"string","pattern":"^[0-9a-f]{64}$"},
                    "verdict":{"type":"string","enum":["matches","rejects"]},
                    "summary":{"type":"string","minLength":1,"maxLength":4096}
                }),
                json!([
                    "request_id",
                    "candidate_set_id",
                    "caller_request_id",
                    "expected_result_revision",
                    "expected_effect_digest",
                    "verdict",
                    "summary"
                ])
            ),
            json!({"request_id":"00000000-0000-4000-8000-000000000003","candidate_set_id":example_id,"caller_request_id":"00000000-0000-4000-8000-000000000002","expected_result_revision":1,"expected_effect_digest":"0".repeat(64),"verdict":"matches","summary":"Saved choice and mapped nodes match the intended plan"}),
        ),
        route!(
            "query",
            "pipeline.open_effect.get",
            "get_pipeline_open_effect",
            "Read the persisted effect of one explicit Slice open for an independent verifier.",
            "Requires a verifier session, the saved Slice ID and its open request ID.",
            "Returns saved Slice, caller receipt, Work node, source and Matrix binding with an effect digest; no state change.",
            "Safe to repeat; use the digest for a separate attestation.",
            object_schema(
                json!({"slice_id":uuid(),"open_request_id":uuid()}),
                json!(["slice_id", "open_request_id"])
            ),
            json!({"slice_id":example_id,"open_request_id":"00000000-0000-4000-8000-000000000002"}),
        ),
        route!(
            "command",
            "pipeline.open_effect.verify",
            "verify_pipeline_open_effect",
            "Append an independent match or rejection of one persisted Slice open.",
            "Requires a verifier session distinct from caller and Matrix owner, exact open request and effect digest.",
            "Appends an immutable observation; it does not complete a phase or call a provider.",
            "Retry with the same request_id and identical fields.",
            object_schema(
                json!({"request_id":uuid(),"slice_id":uuid(),"open_request_id":uuid(),"expected_effect_digest":{"type":"string","pattern":"^[0-9a-f]{64}$"},"verdict":{"type":"string","enum":["matches","rejects"]},"summary":{"type":"string","minLength":1,"maxLength":4096}}),
                json!([
                    "request_id",
                    "slice_id",
                    "open_request_id",
                    "expected_effect_digest",
                    "verdict",
                    "summary"
                ])
            ),
            json!({"request_id":"00000000-0000-4000-8000-000000000003","slice_id":example_id,"open_request_id":"00000000-0000-4000-8000-000000000002","expected_effect_digest":"0".repeat(64),"verdict":"matches","summary":"Persisted open matches the selected pipeline"}),
        ),
        route!(
            "query",
            "pipeline.phase_effect.get",
            "get_pipeline_phase_effect",
            "Read one saved completed phase attempt, output, selected verification plan obligation and backend evidence refs.",
            "Requires an independent verifier session, exact run ID and attempt ID.",
            "Returns a bound material digest; no phase, run or terminal state change.",
            "Safe to repeat; inspect the output before attesting.",
            object_schema(
                json!({"run_id":uuid(),"attempt_id":uuid()}),
                json!(["run_id", "attempt_id"])
            ),
            json!({"run_id":example_id,"attempt_id":"00000000-0000-4000-8000-000000000002"}),
        ),
        route!(
            "command",
            "pipeline.phase_effect.verify",
            "verify_pipeline_phase_effect",
            "Append a verifier-authored pass, fail or unknown observation for one saved completed phase attempt.",
            "Pass/fail require observation content and the exact saved output digest; without independent observation use unknown.",
            "Appends immutable evidence only; it does not advance a phase or run.",
            "Retry with the same request_id and identical fields.",
            object_schema(
                json!({"request_id":uuid(),"run_id":uuid(),"attempt_id":uuid(),"expected_effect_digest":{"type":"string","pattern":"^[0-9a-f]{64}$"},"verdict":{"type":"string","enum":["pass","fail","unknown"]},"observation":{"type":["string","null"],"minLength":32,"maxLength":16384},"observed_output_digest":{"type":["string","null"],"pattern":"^[0-9a-f]{64}$"},"summary":{"type":"string","minLength":1,"maxLength":4096}}),
                json!([
                    "request_id",
                    "run_id",
                    "attempt_id",
                    "expected_effect_digest",
                    "verdict",
                    "summary"
                ])
            ),
            json!({"request_id":"00000000-0000-4000-8000-000000000003","run_id":example_id,"attempt_id":"00000000-0000-4000-8000-000000000002","expected_effect_digest":"0".repeat(64),"verdict":"unknown","summary":"Independent observation unavailable"}),
        ),
        route!(
            "command",
            "engineering.matrix.disposition.record",
            "record_matrix_disposition",
            "Record the agent's explicit selected or blocked decision for an exact Matrix task revision and opportunity.",
            "Requires an authenticated native session, exact task/input/choice-set digests, current opportunity, matching basis and current advice token when basis is after_advice. The actor is derived from the session. A selected choice must be in the saved set; no automatic selection occurs.",
            "Appends an immutable typed disposition and returns its binding, digest and actor/session provenance without raw Jev content.",
            "Retry only with the same request_id and identical fields; use engineering.matrix.disposition.get to resolve an uncertain result.",
            object_schema(
                json!({
                    "request_id":uuid(),
                    "task_id":uuid(),
                    "expected_task_revision":{"type":"integer","minimum":1},
                    "expected_input_digest":{"type":"string","pattern":"^[0-9a-f]{64}$"},
                    "expected_choice_set_digest":{"type":["string","null"],"pattern":"^[0-9a-f]{64}$"},
                    "opportunity_id":uuid(),
                    "basis":{"type":"string","enum":["after_advice","no_call","manual"]},
                    "advice_id":{"type":["string","null"],"format":"uuid"},
                    "advice_digest":{"type":["string","null"],"pattern":"^[0-9a-f]{64}$"},
                    "decision":{"oneOf":[
                        object_schema(json!({"outcome":{"const":"selected"},"selected_choice_id":{"type":"string","minLength":1,"maxLength":4096}}),json!(["outcome","selected_choice_id"])),
                        object_schema(json!({"outcome":{"const":"blocked"},"blocked_reason":{"type":"string","minLength":1,"maxLength":4096}}),json!(["outcome","blocked_reason"]))
                    ]}
                }),
                json!([
                    "request_id",
                    "task_id",
                    "expected_task_revision",
                    "expected_input_digest",
                    "opportunity_id",
                    "basis",
                    "decision"
                ])
            ),
            json!({"request_id":"00000000-0000-4000-8000-000000000002","task_id":example_id,"expected_task_revision":1,"expected_input_digest":"0".repeat(64),"expected_choice_set_digest":null,"opportunity_id":"00000000-0000-4000-8000-000000000003","basis":"no_call","advice_id":null,"advice_digest":null,"decision":{"outcome":"blocked","blocked_reason":"Required facts remain unresolved"}}),
        ),
        route!(
            "command",
            "session.select_worktrees",
            "select_worktrees",
            "Replace this native session's complete selected worktree set.",
            "Requires an authenticated open session and 0 to 100 unique accessible worktree IDs.",
            "Atomically replaces only this session's selection; an invalid member preserves the old set.",
            "Safe to repeat with the same complete set.",
            object_schema(
                json!({"worktree_ids":{"type":"array","items":uuid(),"maxItems":MAX_WORKTREES,"uniqueItems":true}}),
                json!(["worktree_ids"]),
            ),
            json!({"worktree_ids":[]}),
        ),
        route!(
            "command",
            "program.begin",
            "begin_program",
            "Persist one exact original narrative and create a resumable Program draft.",
            "Requires an authenticated open session, a non-nil request_id, and nonblank original input.",
            "Creates one database Program and first immutable input in one transaction.",
            "Repeat only with the same request_id and byte-identical input; changed input conflicts.",
            object_schema(
                json!({"request_id":uuid(),"input":text(),"task_context":super::planning_task_context()}),
                json!(["request_id", "input"]),
            ),
            json!({"request_id":example_id,"input":"Complete original user narrative"}),
        ),
        route!(
            "command",
            "program.save",
            "save_program",
            "Save a revision-checked Program patch and optionally open the same Program.",
            "Requires current revision and input_cursor. Omission preserves nullable text fields; null clears them. complete true requires six coherent fields, no question, and full input coverage.",
            "Atomically updates the Program revision; it does not create Scope or execute work.",
            "On stale or uncertain result, reload program.get and reconcile before retrying.",
            object_schema(
                json!({"program_id":uuid(),"revision":{"type":"integer","minimum":1},"input_cursor":{"type":"integer","minimum":0},"name":nullable_text(),"intent":nullable_text(),"basis":nullable_text(),"boundaries":nullable_text(),"constraints":nullable_text(),"success":nullable_text(),"working_notes":nullable_text(),"pending_question":nullable_text(),"complete":{"type":"boolean","default":false},"consumed_knowledge":super::planning_manifest_guard()}),
                json!(["program_id", "revision", "input_cursor"]),
            ),
            json!({"program_id":example_id,"revision":1,"input_cursor":1,"name":"Example Program","complete":false}),
        ),
        route!(
            "command",
            "program.record_input",
            "record_program_input",
            "Append one complete original reply or correction to a Program.",
            "Requires an authenticated open session, accessible Program, non-nil request_id, and nonblank exact input.",
            "Atomically appends immutable input and advances the Program revision.",
            "Repeat only with the same request_id and byte-identical input.",
            object_schema(
                json!({"program_id":uuid(),"request_id":uuid(),"input":text(),"task_context":super::planning_task_context()}),
                json!(["program_id", "request_id", "input"]),
            ),
            json!({"program_id":example_id,"request_id":"00000000-0000-4000-8000-000000000002","input":"Complete original reply"}),
        ),
        route!(
            "command",
            "program.knowledge.refresh",
            "refresh_program_knowledge",
            "Refresh the immutable Program planning-knowledge context.",
            "Requires the current Program revision and saved input cursor. Omitted task_context preserves the prior normalized context; an explicit object replaces it completely.",
            "Atomically advances the Program revision and records one immutable manifest and exact replay receipt without adding user input or changing Program fields.",
            "Repeat with the same request_id and byte-identical parameters; changed parameters conflict.",
            object_schema(
                json!({"program_id":uuid(),"revision":{"type":"integer","minimum":1},"input_cursor":{"type":"integer","minimum":0},"request_id":uuid(),"task_context":super::planning_task_context()}),
                json!(["program_id", "revision", "input_cursor", "request_id"]),
            ),
            json!({"program_id":example_id,"revision":1,"input_cursor":0,"request_id":"00000000-0000-4000-8000-000000000003"}),
        ),
        route!(
            "command",
            "setup.inspect",
            "inspect_setup",
            "Inspect the fixed AGENTS.md in the current task launch directory.",
            "Requires host authentication and an open session. Omission reports context_unknown. A supplied path must be the known task launch directory and remain within current setup grants.",
            "May bind the verified physical directory in the database and read filesystem state; it never publishes a file.",
            "Safe to repeat. Unknown or unavailable never proves the file absent.",
            object_schema(
                json!({"task_directory":{"type":"string","minLength":1,"maxLength":MAX_SOURCE_PATH_BYTES}}),
                json!([]),
            ),
            json!({"task_directory":"/absolute/task/launch-directory"}),
        ),
        route!(
            "command",
            "setup.begin",
            "begin_setup",
            "Persist one exact narrative and create a setup draft after verified absence.",
            "Requires an authenticated open session, bound granted directory with freshly verified missing AGENTS.md, non-nil request_id, and nonblank exact input.",
            "Creates one database setup and first immutable input; it does not publish a file.",
            "Repeat only with the same request_id and byte-identical input.",
            object_schema(
                json!({"request_id":uuid(),"input":text()}),
                json!(["request_id", "input"]),
            ),
            json!({"request_id":example_id,"input":"Complete original company and work narrative"}),
        ),
        route!(
            "command",
            "setup.save",
            "save_setup",
            "Save a revision-checked setup draft or durable ready intent.",
            "Requires current revision, input_cursor, and ready. Omission preserves nullable patches; null clears. ready true requires coherent content, no pending question, and full input coverage.",
            "Atomically updates only setup state; it does not publish AGENTS.md.",
            "On stale or uncertain result, reload setup.get from input 0 before retrying.",
            object_schema(
                json!({"setup_id":uuid(),"revision":{"type":"integer","minimum":1},"input_cursor":{"type":"integer","minimum":0},"ready":{"type":"boolean"},"content":nullable_text(),"working_notes":nullable_text(),"pending_question":nullable_text()}),
                json!(["setup_id", "revision", "input_cursor", "ready"]),
            ),
            json!({"setup_id":example_id,"revision":1,"input_cursor":1,"ready":false,"content":"# Workspace instructions"}),
        ),
        route!(
            "command",
            "setup.record_input",
            "record_setup_input",
            "Append one complete original reply or correction to a setup.",
            "Requires current setup revision, non-nil request_id, nonblank exact input, current binding, and setup grant.",
            "Atomically appends immutable input and advances the setup revision; it does not publish a file.",
            "Repeat only with the same revision, request_id, and byte-identical input.",
            object_schema(
                json!({"setup_id":uuid(),"revision":{"type":"integer","minimum":1},"request_id":uuid(),"input":text()}),
                json!(["setup_id", "revision", "request_id", "input"]),
            ),
            json!({"setup_id":example_id,"revision":1,"request_id":"00000000-0000-4000-8000-000000000002","input":"Complete original reply"}),
        ),
        route!(
            "query",
            "scope.candidates.context",
            "candidate_context",
            "Read one bounded view of an immutable Scope-candidate context and current stale reasons.",
            "Requires an authenticated open native session and an accessible candidate set. after is omitted for the first whole-entry page; explicit null is invalid.",
            "Reads one consistent database snapshot and compares current Program, selected-source identities, method, rule, and registry revisions. It never refreshes or writes.",
            "Safe to repeat. Follow next_after exactly; use scope.candidates.refresh before a stale write.",
            candidate_schema::context(),
            json!({"candidate_set_id":example_id,"view":"overview","limit":25}),
        ),
        route!(
            "command",
            "scope.candidates.begin",
            "begin_candidate_set",
            "Create or recover the single current Scope-candidate set for one Program.",
            "Requires current Program revision, an explicit finite or ongoing boundary, a non-nil request_id, and exact nonblank planning input.",
            "Atomically captures Program, planning input, selected-source identities, the embedded method, and applicable full rules. It creates no Scope.",
            "The same request and payload returns the same backend IDs. A different begin returns the existing head; changed payload under one request_id conflicts.",
            candidate_schema::begin(),
            json!({"request_id":example_id,"program_id":"00000000-0000-4000-8000-000000000002","program_revision":2,"boundary":"finite","input":"Plan reviewed Scope candidates for this Program."}),
        ),
        route!(
            "command",
            "scope.candidates.save",
            "save_candidate_set",
            "Persist either a Scope-candidate draft with backend-assigned IDs or its semantic review.",
            "Requires the exact candidate-set revision, snapshot_id, input_cursor, and request_id. kind is draft or review. New entities use unique temporary local labels; existing entities copy backend id and revision.",
            "Draft save atomically resolves local references and assigns durable UUIDs. Review save retains every decision and finding and may mark the candidate set review_required, ready, or blocked. Neither opens a Scope.",
            "The same request and payload returns the same assigned IDs before revision checks. A changed payload conflicts. Reload scope.candidates.context after uncertainty.",
            candidate_schema::save(),
            json!({"kind":"draft","candidate_set_id":example_id,"revision":1,"snapshot_id":"00000000-0000-4000-8000-000000000002","input_cursor":1,"request_id":"00000000-0000-4000-8000-000000000003","draft":{"boundary":"finite","goals":[{"identity":{"local":"goal_invite"},"text":"Users can invite a collaborator.","source_ref_id":"00000000-0000-4000-8000-000000000004","resolution":{"kind":"candidate","reference":{"local":"candidate_invite"}}}],"candidates":[{"identity":{"local":"candidate_invite"},"title":"Invite collaborators","outcome":"An authorized user can invite a collaborator.","trigger":"An authorized user submits an invite.","delivered_behavior":"The service records and sends the invitation.","proof":"An integration test observes the accepted invite and delivery.","coverage_goals":[{"local":"goal_invite"}]}]}}),
        ),
        route!(
            "command",
            "scope.candidates.record_input",
            "record_candidate_input",
            "Append one exact amendment to the current planning-request window.",
            "Requires the current candidate-set revision, a non-nil request_id, and nonblank exact input.",
            "Atomically appends immutable raw input and marks the saved context stale until an explicit refresh. Existing history and backend IDs remain intact.",
            "Repeat only with the same request_id and byte-identical input; changed input conflicts.",
            candidate_schema::record_input(),
            json!({"candidate_set_id":example_id,"revision":2,"request_id":"00000000-0000-4000-8000-000000000003","input":"Expire pending invitations after seven days."}),
        ),
        route!(
            "command",
            "scope.candidates.refresh",
            "refresh_candidate_set",
            "Capture a new immutable context snapshot for the current candidate-set head.",
            "Requires current candidate-set and Program revisions and a non-nil request_id. It follows recorded planning amendments and current DB-selected worktree identities.",
            "Atomically stores complete method and applicable rule bodies, Program material, planning inputs, and source references in a new version. It does not inspect Git content or open a Scope.",
            "The same request and payload returns the same snapshot. A changed payload conflicts; stale revisions require a fresh context read.",
            candidate_schema::refresh(),
            json!({"candidate_set_id":example_id,"revision":3,"request_id":"00000000-0000-4000-8000-000000000004","program_revision":2}),
        ),
        route!(
            "command",
            "scope.candidates.delta",
            "scope_candidate_delta",
            "Apply one CAS-protected additive candidate mutation batch.",
            "Requires an authenticated open native session and an accessible candidate set.",
            "Validates and records the complete operation batch atomically with idempotency replay and stale-revision refusal.",
            "Repeat with the exact idempotency key and payload for replay; changed payload conflicts.",
            candidate_schema::delta_apply(),
            json!({"candidate_set_id":example_id,"expected_revision":3,"idempotency_key":"delta-1","operations":[{"operation":"coverage.link","candidate_id":example_id,"goal_id":example_id}]}),
        ),
        route!(
            "query",
            "scope.candidates.delta.status",
            "scope_candidate_delta_status",
            "Read one additive candidate mutation receipt.",
            "Requires an authenticated open native session and an accessible candidate set.",
            "Reads the persisted mutation receipt only.",
            "Safe to repeat.",
            candidate_schema::delta_status(),
            json!({"candidate_set_id":example_id,"idempotency_key":"delta-1"}),
        ),
        route!(
            "query",
            "scope.context",
            "scope_context",
            "Read one opened native Scope without Slice-candidate design guidance.",
            "Requires an authenticated open session and an accessible Scope.",
            "Reads the durable Scope only.",
            "Safe to repeat.",
            slice_schema::scope_context(),
            json!({"scope_id":example_id}),
        ),
        route!(
            "query",
            "slice.pipelines",
            "slice_pipelines",
            "List the seven canonical Slice pipelines and their current execution availability.",
            "Requires host authentication.",
            "Returns refined delivery metadata for executable definitions and explicit stub status for the rest; it starts no run.",
            "Safe to repeat.",
            object_schema(json!({}), json!([])),
            json!({}),
        ),
        route!(
            "query",
            "slice.candidates.context",
            "slice_candidate_context",
            "Read one bounded view of an opened Scope's revisable Slice-candidate plan.",
            "Requires an authenticated open session and accessible Scope. Explicit null after is invalid.",
            "Reads stored planning context and reports current method, rule, catalogue, input, and result staleness.",
            "Safe to repeat; follow returned refresh and paging actions.",
            slice_schema::candidate_context(),
            json!({"scope_id":example_id,"view":"overview","limit":25}),
        ),
        route!(
            "query",
            "slice.context",
            "slice_context",
            "Read one Slice and its selected pipeline label and persisted execution status.",
            "Requires an authenticated open session and an accessible Slice.",
            "Reads the Slice only. It supplies no candidate-design rules and does not claim the backend performed agent work.",
            "Safe to repeat.",
            slice_schema::slice_context(),
            json!({"slice_id":example_id}),
        ),
        route!(
            "command",
            "scope.open",
            "scope_open",
            "Open a native Scope from one current accepted Scope candidate and return its initial Slice-planning context.",
            "Requires exact current candidate-set, snapshot, candidate identity and revision plus a non-nil request_id.",
            "Atomically creates the Scope, initial Slice-candidate set, input, and immutable method/rule/catalogue snapshot. It opens no Slice.",
            "The same request and payload replays the same Scope and planning context.",
            slice_schema::open_scope(),
            slice_schema::open_scope_example(),
        ),
        route!(
            "command",
            "slice.candidates.save",
            "save_slice_candidate_set",
            "Persist either a complete Slice-candidate graph draft or its critical review.",
            "Requires exact Scope, candidate-set, snapshot, cursor, revision, and request identity. Full requires both exceptional-choice explanations. A draft may include an exact Matrix task, disposition, choice, draft-node mapping, and digest binding.",
            "Draft save assigns stable IDs and validates dependencies. An optional Matrix binding records provenance only after the native save succeeds. Review may make a plan ready while retaining intentional Decision nodes.",
            "Replay the same payload only; reload context after uncertainty or stale rejection.",
            slice_schema::save(),
            slice_schema::save_matrix_selection_example(),
        ),
        route!(
            "command",
            "slice.candidates.input",
            "record_slice_candidate_input",
            "Append exact new planning input to a Scope's Slice-candidate plan.",
            "Requires current Scope, candidate-set revision, and non-nil request identity.",
            "Appends immutable input and makes the planning snapshot stale until refresh.",
            "Repeat only with the same request and byte-identical input.",
            slice_schema::record_input(),
            json!({"scope_id":example_id,"candidate_set_id":example_id,"revision":2,"request_id":example_id,"input":"Complete planning correction"}),
        ),
        route!(
            "command",
            "slice.candidates.refresh",
            "refresh_slice_candidate_set",
            "Refresh immutable Slice-candidate guidance and result context before revising future work.",
            "Requires current Scope, candidate-set revision, and non-nil request identity.",
            "Captures current method, all four design rules, versioned catalogue, inputs, and results. Opened work and history remain preserved.",
            "The same request and payload replays; then review affected future work even when unchanged.",
            slice_schema::refresh(),
            json!({"scope_id":example_id,"candidate_set_id":example_id,"revision":3,"request_id":example_id}),
        ),
        route!(
            "command",
            "slice.open",
            "slice_open",
            "Open one Slice from one ready work candidate.",
            "Requires exact current Scope, candidate-set, snapshot, work-candidate identity and revisions with satisfied dependencies. Optional disposition_id must identify a current saved planning decision by this Owner and session for this exact Work, Matrix, source, and manifest binding. Rejected advice cannot select a pipeline. Decision nodes cannot open.",
            "Creates one Slice with one bounded outcome and the accepted or deterministic eligible pipeline kind when a disposition is supplied. Without disposition_id it uses the saved Work pipeline. It injects no design rules and starts no execution.",
            "The same request and payload replays the same Slice.",
            slice_schema::open_slice(),
            slice_schema::open_slice_example(),
        ),
        route!(
            "command",
            "slice.result.record",
            "slice_result_record",
            "Record an externally reported Slice result and return the now-stale future planning context.",
            "Requires exact current Slice revision, non-nil request identity, outcome, summary, direct evidence, scope impact, and remaining work.",
            "Stores observation/evidence, updates Slice state, and marks future planning for refresh and review; TectD does not claim it executed the pipeline.",
            "The same request and payload replays the same result and context.",
            slice_schema::record_result(),
            slice_schema::record_result_example(),
        ),
        route!(
            "query",
            "slice.pipeline.context",
            "slice_pipeline_context",
            "Read one durable Slice pipeline run or one exact immutable phase output selected from it.",
            "Requires an authenticated open session and an accessible run. output view additionally requires exact output_id and digest.",
            "Current view returns pinned guidance and caller-reported evidence, or explicit output references if values exceed capacity. Output view returns one complete untruncated value.",
            "Safe to repeat.",
            slice_schema::pipeline_context(),
            json!({"run_id":example_id}),
        ),
        route!(
            "query",
            "slice.pipeline.instruction",
            "slice_pipeline_instruction",
            "Read one explicitly refreshed pinned pipeline method, instruction, skill, or resource body.",
            "Requires an authenticated open session, an accessible run, and the exact pinned instruction id, version, and digest. Set refresh=true to request the body explicitly.",
            "Reads one immutable instruction snapshot from the run's pinned definition without redelivering the full manifest or mutating the run.",
            "Safe to repeat with the same pinned id, version, digest, and refresh flag.",
            slice_schema::pipeline_instruction(),
            json!({"run_id":example_id,"instruction_id":"slice.lightweight.k1","version":"0.7.0","digest":"794ffddb9a9d7f8d4056fb6bf25f5a5365109be4158f2bb550e081bcf4fcc0a6","refresh":true}),
        ),
        route!(
            "command",
            "slice.pipeline.begin",
            "slice_pipeline_begin",
            "Create or recover the single version-pinned pipeline run for an opened Slice.",
            "Requires exact Slice revision and a task-fit qualification reason. delivery_mode may be omitted to use the returned definition default, or must be one of its allowed modes. definition_version may be supplied to select an immutable provider snapshot, including Lightweight TDD v0.7 K1-K5; omitted or explicit v0.6 keeps the legacy fifteen-phase provider. Research and Deep Brainstorming additionally require an immutable topic level, selector context, and matching completion inquiry; checkpoint-backed Research uses the exact planned checkpoint inquiry.",
            "Persists the resolved mode, rationale, complete immutable definition, and first current phase. It performs no pipeline work.",
            "The same request and byte-identical payload replays the same run; a different request cannot create a second run.",
            slice_schema::pipeline_begin(),
            json!({"request_id":example_id,"scope_id":example_id,"slice_id":example_id,"slice_revision":1,"qualification_reason":"The bounded change fits the default delivery mode."}),
        ),
        route!(
            "command",
            "slice.pipeline.run.migrate",
            "slice_pipeline_run_migrate",
            "Create an immutable v0.7 successor for an explicitly mapped legacy pipeline run.",
            "Requires an accessible legacy run, its exact current revision, an idempotency key, an immutable successor definition version, and one-to-one obligation/evidence mappings.",
            "Atomically inserts a distinct successor run, marks the predecessor superseded, and records mapping digests; the predecessor definition and history remain preserved.",
            "The same idempotency key and payload replay the same migration; a changed payload conflicts.",
            slice_schema::pipeline_run_migrate(),
            json!({"request_id":example_id,"predecessor_run_id":example_id,"expected_revision":1,"idempotency_key":"legacy-migration-1","successor_definition_version":"0.7.0-native.k1k5","mappings":[{"legacy_obligation_id":"phase-01","successor_obligation_id":"k1","evidence_refs":[{"reference":"artifact://evidence/1","digest":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"}]}]}),
        ),
        route!(
            "command",
            "slice.pipeline.phase.complete",
            "slice_pipeline_phase_complete",
            "Record one caller-reported phase attempt and atomically return the next ready action.",
            "Requires exact run revision/current phase and all typed phase fields, verdicts, dispositions, and terminal contract required by the pinned definition. The bounded output body is optional for v0.7 and required by legacy definitions. v0.7 derives proof receipts from backend state; legacy definitions require the exact supplied proof receipts returned by their ready action. B05 waiting_research additionally requires question, answer criteria, Research inquiry, and reason for a separate Research Slice.",
            "Appends an immutable attempt/output, updates only current bindings, and advances or pauses structurally. Only terminal completion, explicit published block, or pipeline escalation writes a Slice Result and stales future planning.",
            "The same request and payload replays. New retries obey the phase retry policy; exact command replay never repeats external work.",
            slice_schema::pipeline_phase_complete(),
            json!({"request_id":example_id,"run_id":example_id,"run_revision":1,"phase_id":"K1","outcome":"completed","transition":"continue","output":{"producer_context_id":"agent-task-context-1","fields":{},"dispositions":[]}}),
        ),
        route!(
            "command",
            "slice.pipeline.input",
            "slice_pipeline_input",
            "Append one exact phase-local operator answer, context, authority record, or resume input.",
            "Requires exact run revision and current unfinished phase. Optional source_amendment is restricted to Full Design phase 5 or later and requires exact current phase-5 predecessor lineage, a changed hash-valid successor artifact, and direct authority scope/provenance in the exact input.",
            "Appends immutable input and resumes the same pinned run without restarting or changing definition history. A valid source amendment retains history, records successor lineage as phase-5 input, stales phase 5 onward, and returns phase 5 current.",
            "The same request and byte-identical payload replays; changed input conflicts.",
            slice_schema::pipeline_input(),
            json!({"request_id":example_id,"run_id":example_id,"run_revision":2,"phase_id":"slice-lightweight-entry-gate","input":"Exact requested context"}),
        ),
        route!(
            "command",
            "slice.pipeline.delivery.escalate",
            "slice_pipeline_delivery_escalate",
            "Change an active run from whole delivery to phasewise delivery at its current unfinished phase.",
            "Requires exact run revision/current phase, whole mode, and a nonblank reason.",
            "Appends a transition receipt and changes future guidance delivery only; prior phase history and the pinned definition remain unchanged.",
            "The same request and payload replays. Phasewise-to-whole reversal is forbidden.",
            slice_schema::pipeline_delivery_escalate(),
            json!({"request_id":example_id,"run_id":example_id,"run_revision":2,"phase_id":"slice-lightweight-entry-gate","reason":"Current context requires bounded phase delivery."}),
        ),
        route!(
            "command",
            "slice.pipeline.checkpoint.resolve",
            "slice_pipeline_checkpoint_resolve",
            "Resolve one exact Deep Brainstorming research checkpoint and return its producer to B05.",
            "Requires the exact current producer revision, checkpoint identity and digest, an action and reason, plus the exact completed Research result and terminal output for accept or reject.",
            "Records an immutable resolution and producer input, then resumes the same producer run at B05. It does not publish knowledge or complete either decision automatically.",
            "The same request and payload replays the same result; changed payload, stale CAS, wrong consumer or wrong result is rejected.",
            slice_schema::pipeline_checkpoint_resolve(),
            json!({"request_id":example_id,"producer_run_id":example_id,"producer_run_revision":6,
                "checkpoint":{"checkpoint_id":example_id,"digest":"sha256"},
                "action":"cancel","reason":"The research question must be reframed."}),
        ),
        route!(
            "execute",
            "setup.apply",
            "apply_setup",
            "Publish the durable ready setup as the fixed AGENTS.md and verify exact bytes.",
            "Requires current authenticated binding/grant and the exact ready setup revision. The complete saved content must be shown before this call.",
            "Exclusively creates AGENTS.md or adopts exact matching bytes, verifies readback, then records applied status. It never overwrites a different file.",
            "After an uncertain result, repeat the same setup_id and ready revision. A changed or removed applied file is preserved as a conflict.",
            object_schema(
                json!({"setup_id":uuid(),"revision":{"type":"integer","minimum":1}}),
                json!(["setup_id", "revision"]),
            ),
            json!({"setup_id":example_id,"revision":2}),
        ),
    ];
    routes.extend(knowledge_schema::routes(example_id));
    routes.extend(knowledge_lifecycle_schema::routes(example_id));
    routes.extend(knowledge_maintenance_schema::routes(example_id));
    routes.push(knowledge_search_schema::route());
    routes.extend(super::advisory_schema::routes(example_id));
    routes.extend([
        route!("command", "slice.pipeline.evidence_artifact.register", "slice_pipeline_evidence_artifact_register", "Register immutable evidence metadata and receive a backend-issued artifact identity.", "Requires an authenticated open native session; the supplied digest, size and provenance describe the exact future bytes.", "Creates an uploading artifact revision; no evidence is ready until finalize succeeds.", "The same request replays the same artifact; changed payload conflicts.", object_schema(json!({"request_id":uuid(),"digest":{"type":"string","pattern":"^[0-9a-fA-F]{64}$"},"size":{"type":"integer","minimum":0},"format":text(),"provenance":text(),"target":text()}), json!(["request_id","digest","size","format","provenance","target"])), json!({"request_id":example_id,"digest":"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa","size":12,"format":"text/plain","provenance":"operator-observed","target":"slice"})),
        route!("command", "slice.pipeline.evidence_artifact.finalize", "slice_pipeline_evidence_artifact_finalize", "Finalize one registered evidence artifact by hashing and sizing the submitted bytes.", "Requires an uploading artifact revision.", "Marks the immutable revision ready only when digest and byte size match; mismatches are durably rejected.", "The same request replays the same final state.", object_schema(json!({"request_id":uuid(),"artifact_id":uuid(),"revision":{"type":"integer","minimum":1},"body":{"type":"string"}}), json!(["request_id","artifact_id","revision","body"])), json!({"request_id":example_id,"artifact_id":example_id,"revision":1,"body":"exact evidence bytes"})),
        route!("query", "slice.pipeline.evidence_artifact.read", "slice_pipeline_evidence_artifact_read", "Read one bounded artifact fragment with explicit completeness and continuation cursor.", "Requires an accessible artifact revision and a positive limit no larger than 65536.", "Reads a bounded fragment and always returns complete plus next_offset when more bytes remain.", "Safe to repeat with the same offset and limit.", object_schema(json!({"artifact_id":uuid(),"revision":{"type":"integer","minimum":1},"offset":{"type":"integer","minimum":0},"limit":{"type":"integer","minimum":1,"maximum":65536}}), json!(["artifact_id","revision"])), json!({"artifact_id":example_id,"revision":1,"offset":0,"limit":65536})),
    ]);
    routes
}
