//! Native host configuration and bounded local transports.

mod advisory_dispatch;
mod advisory_tools;
mod anti_bloat_tools;
mod api;
mod context;
mod frame;
mod git;
pub mod jev_anti_bloat_choice;
mod jev_anti_bloat_provider;
mod jev_json;
pub mod jev_matrix_advice;
mod jev_model_route_provider;
pub mod jev_pipeline_recommendation;
mod jev_scope_advice;
mod knowledge_dispatch;
mod knowledge_embedding;
mod knowledge_lifecycle_definitions;
mod knowledge_lifecycle_dispatch;
mod knowledge_lifecycle_encoding;
mod knowledge_lifecycle_output;
mod knowledge_lifecycle_tools;
mod knowledge_maintenance_dispatch;
mod knowledge_maintenance_output;
mod knowledge_maintenance_tools;
mod knowledge_output;
mod knowledge_search_dispatch;
mod knowledge_search_output;
mod knowledge_search_tools;
mod knowledge_tools;
mod matrix_advisory_tools;
mod matrix_disposition_tools;
mod matrix_planning_effect_tools;
mod matrix_task_tools;
mod matrix_verification_tools;
mod mcp;
mod model_route_catalogue;
mod model_route_host_capabilities;
mod model_route_tools;
mod pipeline_definitions;
mod pipeline_dispatch;
mod pipeline_open_effect_tools;
mod pipeline_output;
mod pipeline_phase_effect_tools;
mod pipeline_recommendation_tools;
mod pipeline_tools;
mod program_output;
mod program_tools;
mod response_diet;
mod responses;
mod scope_candidate_dispatch;
mod scope_candidate_output;
mod scope_candidate_tools;
mod scope_guidance;
mod setup_dispatch;
mod setup_files;
mod setup_output;
mod setup_recovery;
mod setup_tools;
mod slice_dispatch;
mod slice_guidance;
mod slice_pipeline_catalog;
mod slice_tools;
mod system_one_transport;
mod tools;
mod transport;
mod workspace_output;

pub use context::{HostContext, host_context_from_env, read_host_auth_file};
pub use git::GitSourceInspector;
pub use jev_anti_bloat_provider::{JevAntiBloatConfig, JevAntiBloatProvider};
pub use jev_model_route_provider::{JevModelRouteConfig, JevModelRouteProvider};
pub use jev_scope_advice::{JevScopeAdviceConfig, JevScopeAdviceProvider};
pub use knowledge_embedding::{LocalEmbeddingConfig, LocalKnowledgeEmbeddingWorker};
pub use mcp::run_stdio;
pub use model_route_catalogue::StaticModelRouteCatalogue;
pub use model_route_host_capabilities::StaticModelRouteHostCapabilities;
pub use pipeline_definitions::StaticPipelineRecommendationDefinitions;
#[doc(hidden)]
pub use scope_guidance::CandidateEncoding;
pub use scope_guidance::StaticCandidateGuidance;
pub use setup_files::LocalSetupFiles;
#[doc(hidden)]
pub use slice_dispatch::NativePlanningEncoding;
pub use transport::{call, call_tool, serve};

pub type Result<T> = tect_domain::Result<T>;
